# AI Agent Driver
ai_agent_driver: ai-team-flow-dev

# Project Folder
workspace: /TopsailAI/src/topsailai

# Context Informations, key is item name, value is list for files
context:
  _default:
    - project.yaml
    - readme.md
    - workspace/readme.md

  default: []

  test:
    - test.md

  llm_mistake:
    - ai_base/llm_control/llm_mistakes/readme.md
    - ai_base/llm_hooks/hook_after_chat/README.md
