# AI Agent Driver
ai_agent_driver: ai-team-flow-dev

# Project Folder
workspace: /TopsailAI/src/topsailai

# Context Informations, key is item name, value is list for files
context:
  _default:
    - project.yaml
    - workspace/readme.md
    - docs/Environment_Variables.md # env_template
    - MEMO.md
    - LEARN.md

  default: []

  agent:
    - MEMO.CommonUtils.md
    - MEMO.AgentCore.md
    - MEMO.AgentWorkers.md

  tools:
    - tools/readme.md

  test:
    - test.md

  llm_mistake:
    - ai_base/llm_control/llm_mistakes/readme.md
    - ai_base/llm_hooks/hook_after_chat/README.md

  approval:
    - features/91-tool_approval.md

  events:
    - events/README.md

# Environment variable configuration: each item can define its own environment variables
# _default is the base environment variables shared by all items
environment:
  _default:
    TOPSAILAI_INTERACTIVE_MODE: "1"

  memo:
    TOPSAILAI_AGENT_DRIVER: "topsailai_agent_chats"
