"""
Constants module for AI Agent framework.

This module defines common constants used throughout the AI Agent framework,
primarily role definitions for message handling in conversational AI systems.
"""

# Role definitions for message types in conversational AI systems
# These roles are used to categorize messages in the conversation history
ROLE_USER = "user"        # Messages from the human user
ROLE_ASSISTANT = "assistant"  # Messages generated by the AI assistant
ROLE_SYSTEM = "system"    # System-level messages and prompts
ROLE_TOOL = "tool"        # Messages containing tool execution results


# QOS Keywords for monitoring
# LLM mistake keyword
LLM_KEYWORD_MISTAKE = "LLM Mistake"
# LLM service keyword
LLM_KEYWORD_SERVICE = "LLM Service"

# default seconds
DEFAULT_LLM_SLOW_CHAT_THRESHOLD = 60

# context messages
NON_SYSTEM_PROMPT_MESSAGE_INDEX = 3

# step name
STEP_NAME_TASK = "task"
STEP_NAME_ACTION = "action"
STEP_NAME_THOUGHT = "thought"
STEP_NAME_INQUIRY = "inquiry"
STEP_NAME_FINAL = "final"
STEP_NAME_FINAL_ANSWER = "final_answer"
STEP_NAME_OBSERVATION = "observation"

# message content key
MSG_KEY_STEP_NAME = "step_name"
MSG_KEY_RAW_TEXT = "raw_text"
MSG_KEY_TOOL_CALL = "tool_call"
MSG_KEY_TOOL_ARGS = "tool_args"
