'''
Author: DawsonLin
Email: lin_dongsen@126.com
Created: 2026-03-26
Purpose: Change CWD to WORK_FOLDER, then load dotenv

1. TOPSAILAI_HOME, refer to `workspace/folder_constants.py`, Files generated by the Agent process, including of `log`, `lock`, `task`, `story_memory` etc..
2. TOPSAILAI_WORK_FOLDER, The working directory of the Agent process, including of `.env`, `db` etc..
'''

import os
from dotenv import load_dotenv

# Original Environ
_env_topsailai_use_tool_calls = os.getenv("TOPSAILAI_USE_TOOL_CALLS")

from topsailai.workspace import folder_constants

# SYSTEM home folder
HOME_FOLDER = os.getenv("HOME") or ""

# TopsailAI home folder
TOPSAILAI_HOME = folder_constants.TOPSAILAI_HOME

# TopsailAI work folder
TOPSAILAI_WORK_FOLDER=""

for WORK_FOLDER in [
    folder_constants.TOPSAILAI_HOME,
    os.path.join(HOME_FOLDER, ".topsailai"),
    os.getcwd(),
]:
    env_file = os.path.join(WORK_FOLDER, ".env")
    if os.path.isdir(WORK_FOLDER) and os.path.exists(env_file):
        os.chdir(WORK_FOLDER)
        os.environ["TOPSAILAI_WORK_FOLDER"] = WORK_FOLDER
        os.environ["PWD"] = WORK_FOLDER
        load_dotenv(env_file)
        TOPSAILAI_WORK_FOLDER = WORK_FOLDER
        break

def customize_for_llm():
    """ Customize according to the large model """
    from topsailai.logger import logger

    # case: TOPSAILAI_USE_TOOL_CALLS
    if _env_topsailai_use_tool_calls is None:
        model_name = os.getenv("OPENAI_MODEL", "").lower()
        for _key in [
            "minimax",
        ]:
            if not model_name:
                break

            if model_name.startswith(_key):
                os.environ["TOPSAILAI_USE_TOOL_CALLS"] = "1"
                logger.warning("Force to set TOPSAILAI_USE_TOOL_CALLS=1 due to LLM Model is [%s]", model_name)

    return

def init_after_loading_dotenv():
    """ Init something """
    customize_for_llm()

# init
os.makedirs(folder_constants.FOLDER_LOG, exist_ok=True)
load_dotenv()

init_after_loading_dotenv()
