'''
Author: DawsonLin
Email: lin_dongsen@126.com
Created: 2026-03-26
Purpose: Change CWD to WORK_FOLDER, then load dotenv

Environment variables used by this module:

1. TOPSAILAI_HOME
   Files generated by the Agent process, including `log`, `lock`, `task`,
   `story_memory`, etc. It defines the agent's working environment.
   Refer to `workspace/folder_constants.py` for the default path and resolution.

2. TOPSAILAI_WORK_FOLDER
   The working directory of the Agent process, including `.env`, `db`, etc.
   It is a working environment of the agent.
   NOTE: This variable cannot be set manually; it is set automatically when the
   process starts by the auto-discovery logic below.

3. TOPSAILAI_PROJECT_WORKSPACE (alias: TOPSAILAI_PROJECT_FOLDER)
   The project folder is the permission range that the agent can actively read
   and write files within.

4. TOPSAILAI_PWD (alias: TOPSAILAI_PROJECT_PWD)
   Print Working Directory, i.e. the folder at the time of process startup.
   It is captured and injected into the environment prompt (see
   `context/prompt_env.py`) so the agent knows its startup working directory.
   NOTE: This variable is set automatically at process startup. Do not set it
   manually.
'''

import os
from dotenv import load_dotenv


############################################################################
# ORIGINAL Environment
############################################################################

# Original Environ
_env_topsailai_use_tool_calls = os.getenv("TOPSAILAI_USE_TOOL_CALLS")


############################################################################
# TopsailAI Base Runtime
############################################################################

from topsailai.workspace import folder_constants

# TopsailAI home folder
TOPSAILAI_HOME = folder_constants.TOPSAILAI_HOME

# TopsailAI work folder
# This variable is set automatically at process startup. Do not set it manually.
TOPSAILAI_WORK_FOLDER=TOPSAILAI_HOME

def __set_work_folder(work_folder:str):
    os.environ["TOPSAILAI_WORK_FOLDER"] = work_folder
    os.environ["PWD"] = work_folder
    os.chdir(work_folder)
    return
__set_work_folder(TOPSAILAI_WORK_FOLDER)

def __load_env():
    # sequence required
    for env_name in [
        ".env.local",
        ".env",
    ]:
        env_file = os.path.join(TOPSAILAI_WORK_FOLDER, env_name)
        if os.path.exists(env_file):
            load_dotenv(env_file)
__load_env()


############################################################################
# TopsailAI Custom
############################################################################

def customize_for_llm():
    """ Customize according to the large model """
    from topsailai.logger import logger

    # case: TOPSAILAI_USE_TOOL_CALLS
    if _env_topsailai_use_tool_calls is None:
        model_name = os.getenv("OPENAI_MODEL", "").lower()
        prefixes = os.getenv(
            "TOPSAILAI_USE_TOOL_CALLS_MODEL_PREFIXES",
            "minimax,gpt",
        )
        for _key in [
            p.strip().lower()
            for p in prefixes.split(",")
            if p.strip()
        ]:
            if not model_name:
                break

            if model_name.startswith(_key):
                os.environ["TOPSAILAI_USE_TOOL_CALLS"] = "1"
                logger.warning("Force to set TOPSAILAI_USE_TOOL_CALLS=1 due to LLM Model is [%s]", model_name)

    return

def init_after_loading_dotenv():
    """ Init something """
    customize_for_llm()

    # log
    env_info = dict(
        TOPSAILAI_HOME=TOPSAILAI_HOME,
        TOPSAILAI_WORK_FOLDER=TOPSAILAI_WORK_FOLDER,
        TOPSAILAI_PROJECT_WORKSPACE=os.getenv("TOPSAILAI_PROJECT_WORKSPACE"),
        TOPSAILAI_PWD=os.getenv("TOPSAILAI_PWD"),
    )
    from topsailai.logger import logger
    logger.info("Folder Environment: %s", env_info)

# init
os.makedirs(folder_constants.FOLDER_LOG, exist_ok=True)
load_dotenv()

init_after_loading_dotenv()
