# Project Options for TopsailAI
programming_language: python
workspace: /TopsailAI/src/topsailai
Note:
  - |
    > Factual Info MUST SYNC:
    When there are changes to the environment variables, these files also need to be updated: `env_template`, `docs/Environment_Variables.md`;
  - |
    > How to run all of Unit Tests:
    You should call `tests/run_tests.py` instead of call `pytest tests/unit`,
    If you call `pytest tests/unit` to run ALL will inevitably fail!
    Call single `pytest tests/unit/xxx.py` is OK.
