'''
  Author: DawsonLin
  Email: lin_dongsen@126.com
  Created: 2025-10-22
  Purpose: Token counting and statistics utilities for LLM interactions

  This module provides utilities for token counting and statistics tracking
  in Large Language Model (LLM) interactions. It includes functions for
  counting tokens in text and a thread-based statistics tracker for
  monitoring token usage over time.
'''

import time
import threading
from collections import deque
from typing import Optional

import tiktoken

from topsailai.logger.log_chat import logger
from topsailai.utils.print_tool import print_info
from topsailai.utils import (
    env_tool,
)
#####################################################################
# Wrapper: `from openai.types.completion_usage import CompletionUsage`
# The import time is too long!
#####################################################################


class BaseModel(object):
    pass

class CompletionTokensDetails(BaseModel):
    """Breakdown of tokens used in a completion."""

    accepted_prediction_tokens: Optional[int] = None
    """
    When using Predicted Outputs, the number of tokens in the prediction that
    appeared in the completion.
    """

    audio_tokens: Optional[int] = None
    """Audio input tokens generated by the model."""

    reasoning_tokens: Optional[int] = None
    """Tokens generated by the model for reasoning."""

    rejected_prediction_tokens: Optional[int] = None
    """
    When using Predicted Outputs, the number of tokens in the prediction that did
    not appear in the completion. However, like reasoning tokens, these tokens are
    still counted in the total completion tokens for purposes of billing, output,
    and context window limits.
    """


class PromptTokensDetails(BaseModel):
    """Breakdown of tokens used in the prompt."""

    audio_tokens: Optional[int] = None
    """Audio input tokens present in the prompt."""

    cached_tokens: Optional[int] = None
    """Cached tokens present in the prompt."""


class CompletionUsage(BaseModel):
    """Usage statistics for the completion request."""

    completion_tokens: int
    """Number of tokens in the generated completion."""

    prompt_tokens: int
    """Number of tokens in the prompt."""

    total_tokens: int
    """Total number of tokens used in the request (prompt + completion)."""

    completion_tokens_details: Optional[CompletionTokensDetails] = None
    """Breakdown of tokens used in a completion."""

    prompt_tokens_details: Optional[PromptTokensDetails] = None
    """Breakdown of tokens used in the prompt."""


#####################################################################
# Functional
#####################################################################


def count_tokens(text, encoding_name="cl100k_base"):
    """
    Count the number of tokens in the given text using the specified encoding.

    This function uses the tiktoken library to encode text and count tokens,
    which is essential for managing LLM API costs and context window limits.

    Args:
        text (str): The text to count tokens for. Can be any string content.
        encoding_name (str): The encoding name to use. Defaults to "cl100k_base"
                           which is commonly used for GPT-4 and newer models.

    Returns:
        int: The number of tokens in the text. Returns 0 if encoding fails.

    Raises:
        Exception: Propagates any exceptions from tiktoken encoding,
                  but catches them and returns 0 with a warning log.

    Example:
        >>> count_tokens("Hello world")
        2
        >>> count_tokens("Hello world", "gpt2")
        3
    """
    try:
        # Get the encoding object for the specified encoding name
        encoding = tiktoken.get_encoding(encoding_name)

        # Encode the text into tokens and count the length
        tokens = encoding.encode(text)
        return len(tokens)

    except Exception as e:
        # Log warning and return 0 if token counting fails
        logger.warning(f"failed to count tokens: {e}")
        return 0


def count_tokens_for_model(text, model_name="gpt-4"):
    """
    Count tokens for a specific model using its default encoding.

    This function automatically selects the appropriate encoding for the
    specified model, making it convenient for model-specific token counting.

    Args:
        text (str): The text to count tokens for.
        model_name (str): The model name to get encoding for.
                         Defaults to "gpt-4".

    Returns:
        int: The number of tokens in the text. Returns 0 if encoding fails.

    Raises:
        Exception: Propagates any exceptions from tiktoken encoding,
                  but catches them and returns 0 with a warning log.

    Example:
        >>> count_tokens_for_model("Hello world", "gpt-4")
        2
        >>> count_tokens_for_model("Hello world", "gpt-3.5-turbo")
        2
    """
    try:
        # Get the encoding specifically designed for the model
        encoding = tiktoken.encoding_for_model(model_name)

        # Encode the text and count the resulting tokens
        tokens = encoding.encode(text)
        return len(tokens)

    except Exception as e:
        # Log warning and return 0 if model-specific encoding fails
        logger.warning(f"failed to count tokens: {e}")
        return 0


class TokenStat(threading.Thread):
    """
    Token statistics thread class for tracking token usage in LLM interactions.

    This class runs as a background thread to monitor and accumulate token counts
    and text lengths for messages sent to LLMs. It's particularly useful for:
    - Monitoring API usage and costs
    - Tracking conversation complexity
    - Managing context window limits
    - Performance monitoring and optimization

    The thread automatically manages its lifecycle based on configured lifetime
    and idle time, ensuring efficient resource usage.

    Attributes:
        total_count (int): Total accumulated token count across all messages
        current_count (int): Token count for the most recent message
        total_text_len (int): Total accumulated text length in characters
        current_text_len (int): Text length for the most recent message
        msg_count (int): Number of messages processed
        total_cached_tokens (int): Total accumulated cached tokens across all messages
        _start_time (int): Timestamp when the thread was started
        _end_time (int): Timestamp when the thread should end (0 for infinite)
        _last_msg_time (int): Timestamp of the last message processed
        buffer: Temporary storage for incoming messages
        rlock (threading.RLock): Reentrant lock for thread-safe operations
        flag_running (bool): Control flag for thread execution
        first_byte_sum_ms (float): Sum of first-byte times for stream responses
        first_byte_count (int): Number of stream responses with first-byte timing
        first_byte_max_ms (float|None): Maximum first-byte time observed
        first_byte_min_ms (float|None): Minimum first-byte time observed
    """

    def __init__(self, llm_id: str, lifetime: int = 86400):
        """
        Initialize the TokenStat thread.

        Sets up the thread with proper naming, timing controls, and initializes
        all statistical counters to zero.

        Args:
            llm_id (str): LLM identifier used for thread naming and logging.
                         Helps distinguish between multiple LLM instances.
            lifetime (int): Thread lifetime in seconds.
                          - Values <= 0: Run forever (infinite lifetime)
                          - Values > 0: Run for specified seconds plus 60s buffer
                          Defaults to 86400 seconds (24 hours).

        Note:
            The thread is started automatically upon initialization as a daemon thread.
        """
        # Initialize timing controls
        self._start_time = int(time.time())
        self._end_time = 0
        if lifetime > 0:
            # Add 60 seconds buffer to the specified lifetime
            self._end_time = self._start_time + lifetime + 60
        self._last_msg_time = 0

        # Initialize parent thread class with daemon flag and descriptive name
        super(TokenStat, self).__init__(name=f"TokenStat:{llm_id}", daemon=1)

        # Initialize statistical counters
        self.total_count = 0        # Total prompt tokens across all requests
        self.current_count = 0      # Prompt tokens in current/last request
        self.current_local_count = 0  # Local estimate for current/last request
        self.current_response_count = None  # Provider prompt tokens when available
        self.current_count_source = "local_estimate"
        self._current_count_finalized = False

        self.total_completion_count = 0  # Total completion tokens across requests
        self.current_completion_count = 0  # Completion tokens in current/last request

        self.total_text_len = 0     # Total characters across all messages
        self.current_text_len = 0   # Characters in current/last message

        self.msg_count = 0          # Number of messages processed

        # From LLM
        self.total_cached_tokens = 0  # Total cached prompt tokens across requests
        self.current_cached_tokens = 0
        # Thread synchronization and data management
        self.buffer = deque()       # Pending message batches
        self.rlock = threading.RLock()  # Reentrant lock for thread safety
        self._batch_condition = threading.Condition(self.rlock)
        self._next_batch_ticket = 0
        self._completed_batch_ticket = 0
        self._current_batch_ticket = None
        self._finalized_batch_ticket = 0

        self.flag_running = True    # Control flag for thread execution

        # First-byte timing statistics for stream responses (milliseconds)
        self.first_byte_sum_ms = 0.0
        self.first_byte_count = 0
        self.first_byte_max_ms = None
        self.first_byte_min_ms = None

        # Start the thread automatically
        self.start()

    @property
    def current_tokens(self):
        """Return current prompt tokens for backward compatibility."""
        return self.current_count

    @property
    def current_prompt_tokens(self):
        """Return prompt tokens in the current or most recent request."""
        return self.current_count

    @property
    def current_completion_tokens(self):
        """Return completion tokens in the current or most recent request."""
        return self.current_completion_count

    @property
    def current_total_tokens(self):
        """Return prompt plus completion tokens for the current request."""
        return self.current_prompt_tokens + self.current_completion_tokens

    @property
    def total_tokens(self):
        """Return cumulative prompt tokens for backward compatibility."""
        return self.total_count

    @property
    def total_prompt_tokens(self):
        """Return cumulative prompt tokens across finalized requests."""
        return self.total_count

    @property
    def total_completion_tokens(self):
        """Return cumulative completion tokens across finalized requests."""
        return self.total_completion_count

    @property
    def total_usage_tokens(self):
        """Return cumulative prompt plus completion tokens."""
        return self.total_prompt_tokens + self.total_completion_tokens

    @property
    def uncached_tokens(self):
        """Return uncached prompt tokens, or None until cache usage is measured."""
        if self.current_cached_tokens is None:
            return None
        return max(0, self.current_prompt_tokens - self.current_cached_tokens)

    @staticmethod
    def _valid_token_count(value):
        """Return a valid non-negative token count, otherwise None."""
        if isinstance(value, int) and not isinstance(value, bool) and value >= 0:
            return value
        return None

    def finalize_usage(
        self,
        usage: CompletionUsage = None,
        ticket: Optional[int] = None,
        completion_text: Optional[str] = None,
    ):
        """Finalize and persist usage, estimating missing completion tokens."""
        with self.rlock:
            ticket = self._current_batch_ticket if ticket is None else ticket
            if ticket is None:
                if self._current_count_finalized:
                    return False
            elif ticket <= self._finalized_batch_ticket:
                return False
            if ticket != self._current_batch_ticket:
                return False

            response_prompt_tokens = None
            response_completion_tokens = None
            if usage is not None:
                response_prompt_tokens = self._valid_token_count(
                    getattr(usage, "prompt_tokens", None)
                )
                response_completion_tokens = self._valid_token_count(
                    getattr(usage, "completion_tokens", None)
                )

                self.current_cached_tokens = None
                prompt_details = getattr(usage, "prompt_tokens_details", None)
                if prompt_details is not None:
                    cached_tokens = self._valid_token_count(
                        getattr(prompt_details, "cached_tokens", None)
                    )
                    if cached_tokens is not None:
                        self.current_cached_tokens = cached_tokens

            self.current_response_count = response_prompt_tokens
            if response_prompt_tokens is not None:
                self.total_count += response_prompt_tokens - self.current_local_count
                self.current_count = response_prompt_tokens
                self.current_count_source = "llm_response"
            else:
                self.current_count_source = "local_estimate"

            if response_completion_tokens is None:
                response_completion_tokens = count_tokens(completion_text) if completion_text else 0
            self.current_completion_count = response_completion_tokens
            self.total_completion_count += self.current_completion_count
            if self.current_cached_tokens:
                self.total_cached_tokens += self.current_cached_tokens
            self._current_count_finalized = True
            if ticket is not None:
                self._finalized_batch_ticket = ticket

            current_prompt_tokens = self.current_prompt_tokens
            current_completion_tokens = self.current_completion_tokens
            current_cached_tokens = self.current_cached_tokens

        # A session may be processed by multiple agents. Persist only this
        # finalized request's deltas and keep the legacy token column prompt-only.
        try:
            from topsailai.context import ctx_manager
            session_id = env_tool.get_session_id()
            if session_id:
                session_mgr = ctx_manager.get_session_manager()
                if session_mgr:
                    session_mgr.accumulate_session_tokens(
                        session_id=session_id,
                        current_tokens=current_prompt_tokens,
                        current_cached_tokens=current_cached_tokens or 0,
                        current_completion_tokens=current_completion_tokens,
                    )
        except Exception as e:
            logger.warning(f"finalize_usage: failed to accumulate session tokens: {e}")
        return True

    def get_token_stat_info(self):
        """Return a snapshot of explicit token metrics."""
        with self.rlock:
            return dict(
                current_prompt_tokens=self.current_prompt_tokens,
                current_completion_tokens=self.current_completion_tokens,
                current_total_tokens=self.current_total_tokens,
                cached_tokens=self.current_cached_tokens,
                uncached_prompt_tokens=self.uncached_tokens,
                msg_count=self.msg_count,
                current_text_len=self.current_text_len,
                total_cached_tokens=self.total_cached_tokens,
                total_text_len=self.total_text_len,
                total_prompt_tokens=self.total_prompt_tokens,
                total_completion_tokens=self.total_completion_tokens,
                total_usage_tokens=self.total_usage_tokens,
                first_byte_avg_sec=(
                    round(self.first_byte_sum_ms / self.first_byte_count / 1000, 3)
                    if self.first_byte_count > 0 else None
                ),
                first_byte_max_sec=(
                    round(self.first_byte_max_ms / 1000, 3)
                    if self.first_byte_max_ms is not None else None
                ),
                first_byte_min_sec=(
                    round(self.first_byte_min_ms / 1000, 3)
                    if self.first_byte_min_ms is not None else None
                ),
            )

    def print_token_stat(self):
        """Print the latest finalized token statistics without mutating them."""
        if env_tool.is_need_print():
            print(flush=True)
        print_info(f"[TokenStat] {self.get_token_stat_info()}")
        if env_tool.is_need_print():
            print(flush=True)

    def output_token_stat(self, usage: CompletionUsage = None):
        """Finalize and print usage as a backward-compatible convenience API."""
        self.finalize_usage(usage)
        self.print_token_stat()

    def add_first_byte(self, first_byte_ms: float):
        """
        Record first-byte timing for a stream response.

        This method updates the cumulative first-byte timing statistics used
        to compute average, maximum, and minimum first-byte response times.
        It is safe to call from any thread.

        Args:
            first_byte_ms (float): Time from request start to first chunk,
                                   in milliseconds. Values that are None or
                                   negative are ignored.

        Returns:
            None
        """
        if first_byte_ms is None or first_byte_ms < 0:
            return

        with self.rlock:
            self.first_byte_sum_ms += first_byte_ms
            self.first_byte_count += 1
            if self.first_byte_max_ms is None or first_byte_ms > self.first_byte_max_ms:
                self.first_byte_max_ms = first_byte_ms
            if self.first_byte_min_ms is None or first_byte_ms < self.first_byte_min_ms:
                self.first_byte_min_ms = first_byte_ms

    def add_msgs(self, msgs, reset_cached_tokens: bool = True):
        """
        Add messages to the buffer for token calculation.

        This method places messages in the buffer for asynchronous processing
        by the thread. The actual token counting happens in the background thread.

        Args:
            msgs: Messages to be sent to the LLM. Can be:
                 - A list of messages (for multi-message interactions)
                 - A single string message
                 - Any object that can be converted to string
            reset_cached_tokens (bool): Reset the cache metric to zero while
                preparing a normal LLM request. Set to False after rebuilding
                context locally to mark cache usage as unknown until the next
                server response.

        Returns:
            int: Monotonically increasing ticket for this calculation batch.

        Note:
            The method updates the last message timestamp and resets locally
            calculated message counters.
        """
        # Use lock for thread-safe buffer operations
        with self._batch_condition:
            self._next_batch_ticket += 1
            ticket = self._next_batch_ticket
            self._current_batch_ticket = ticket

            # Store messages in FIFO order for background processing.
            self.buffer.append((ticket, msgs))

            # Update message count and reset current request counters.
            self.msg_count = len(msgs)
            self.current_count = 0
            self.current_local_count = 0
            self.current_response_count = None
            self.current_completion_count = 0
            self.current_count_source = "local_estimate"
            self._current_count_finalized = False
            self.current_text_len = 0
            self.current_cached_tokens = 0 if reset_cached_tokens else None

            # Update timestamp for last message activity
            self._last_msg_time = int(time.time())
            self._batch_condition.notify()
            return ticket

    def wait(self, ticket: int, timeout: Optional[float] = 1.0) -> bool:
        """Wait until the specified token-calculation batch is complete.

        Args:
            ticket (int): Batch ticket returned by :meth:`add_msgs`.
            timeout (float|None): Maximum seconds to wait. ``None`` waits
                indefinitely.

        Returns:
            bool: True when the batch completed, otherwise False on timeout.
        """
        if ticket is None:
            return True

        with self._batch_condition:
            completed = self._batch_condition.wait_for(
                lambda: self._completed_batch_ticket >= ticket,
                timeout=timeout,
            )

        if not completed:
            logger.warning(
                "TokenStat timed out waiting for batch %s after %s seconds",
                ticket,
                timeout,
            )
        return completed

    def run(self):
        """
        Main thread loop for processing token statistics.

        This method runs in a separate thread and continuously monitors
        the buffer for new messages to process. It handles:
        - Token counting for incoming messages
        - Thread lifecycle management based on lifetime and idle time
        - Resource cleanup and graceful shutdown

        The loop runs with a 10ms sleep interval to balance responsiveness
        and CPU usage efficiency.
        """
        # Set running flag to indicate thread is active
        self.flag_running = True

        # Control frequency for lifetime checks
        count_freq = 0
        need_freq = False
        if self._end_time:
            need_freq = True

        # Maximum idle time before considering shutdown (10 minutes)
        max_idle_time = 600

        def check():
            """
            Check if the thread should continue running.

            This internal function evaluates thread termination conditions:
            - If lifetime has been reached and sufficient idle time has passed
            - If the thread should continue processing

            Returns:
                bool: True if thread should continue, False if it should stop
            """
            # Check if lifetime limit has been configured
            if self._end_time:
                now_ts = int(time.time())
                # Check if current time exceeds end time
                if self._end_time < now_ts:
                    # Additional check: ensure sufficient idle time has passed
                    if now_ts - self._last_msg_time > max_idle_time:
                        logger.info("quit due to lifetime is reached")
                        return False
                    # If LLM might still be in use, continue running
                    # This handles cases where tools are still processing

            return True

        # Main thread execution loop
        while self.flag_running:
            # Perform lifetime check periodically if needed
            if need_freq:
                count_freq += 1
                # Check every 10 seconds (1000 iterations * 0.01 sleep)
                if count_freq > 1000:
                    count_freq = 0
                    if not check():
                        break

            # Short sleep to prevent excessive CPU usage
            time.sleep(0.01)

            # Take the next buffered batch, including empty messages.
            with self._batch_condition:
                if not self.buffer:
                    continue
                ticket, buffer = self.buffer.popleft()

            # Count outside the lock so waiters can honor their timeout.
            if not isinstance(buffer, str):
                buffer = str(buffer)
            current_text_len = len(buffer)
            current_count = count_tokens(buffer)

            # Publish the completed batch atomically before notifying waiters.
            with self._batch_condition:
                is_current = ticket == self._current_batch_ticket
                is_finalized = ticket <= self._finalized_batch_ticket
                if is_current and not is_finalized:
                    self.current_text_len = current_text_len
                    self.current_local_count = current_count
                    self.current_count = current_count
                self.total_count += current_count
                self.total_text_len += current_text_len
                self._completed_batch_ticket = ticket
                self._batch_condition.notify_all()

        # Thread cleanup and exit logging
        logger.info(f"TokenStat is exited: {self.name}")
