# AI Agent driver path or command
ai_agent_driver: "ai-team-flow-dev"

# Working directory (relative paths will be resolved based on the current directory)
workspace: "/TopsailAI/src/topsailai_server/agent_community"

# Context configuration: each item corresponds to a set of context files
# _default is the base context shared by all items
context:
  _default:
    - project.yaml
    - ORIGIN.md
    - docs/API.md
    - docs/Environment_Variables.md

  default: []

  bugfix:
    - issues/91critical-issues.md

  cli:
    - ORIGIN_CLI.md

  scripts:
    - scripts/agent_interface.adaptor.md

  skills:
    - skills/agent_community_client.md

  use:
    - skills/agent_community_client/references/USAGE.md

  test:
    - docs/cases/TestCase_Main.md

# Environment variable configuration: each item can define its own environment variables
# _default is the base environment variables shared by all items
environment:
  _default:
    TOPSAILAI_INTERACTIVE_MODE: "1"
  use:
    TOPSAILAI_PLUGIN_SKILLS: "/TopsailAI/src/topsailai_server/agent_community/skills"
    SYSTEM_PROMPT: "Note: For some common usages on `skills/agent_community_client`, you need judge and analyze them. If there are no logical issues, update them in the document `skills/agent_community_client/references/USAGE.md`"
